backend:
  name: git-gateway
  branch: master
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
local_backend: true
collections:
  - label: "SN&PT"
    name: "SN&PT"
    editor:
      preview: false
    files:
      - label: "SN&PT"
        name: "profile"
        file: "_data/team.yaml"
        fields:
          - label: Jogador
            name: profile
            widget: list
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
  - label: "Portugal I"
    name: "PTI"
    editor:
      preview: false
    files:
      - label: "Portugal I"
        name: "profilepti"
        file: "_data/pti.yaml"
        fields:
          - label: Jogador
            name: profilepti
            widget: list
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
  - label: "Portugal II"
    name: "PTII"
    editor:
      preview: false
    files:
      - label: "Portugal II"
        name: "profileptii"
        file: "_data/ptii.yaml"
        fields:
          - label: Jogador
            name: profileptii
            widget: list
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
  - label: "Portugal III"
    name: "PTIII"
    editor:
      preview: false
    files:
      - label: "Portugal III"
        name: "profileptiii"
        file: "_data/ptiii.yaml"
        fields:
          - label: Jogador
            name: profileptiii
            widget: list
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
  - label: "Academia"
    name: "academia"
    editor:
      preview: false
    files:
      - label: "Academia"
        name: "profileacademia"
        file: "_data/academia.yaml"
        fields:
          - label: Jogador
            name: profileacademia
            widget: list
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
